# Week 2 Challenge 3

DS 2023 | Communicating with Data

In this week's challenge, read the data URL provided into a dataframe and then convert it into a wide table using both the pivoting method and the unstacking method.

The dataset has two grouping columns and one measurement column.

You may not use the general function provided in the notebook we went over in class, but you may certainly apply the pattern it contains. 

Remember that you first need to determine if the grouping column combindations are unique over the observations.

To get credit for this activity, push your notebook to your course repo and submit the URL to Canvas.

Submit your work regardless of if you completed the task.

**You are encouraged to work in groups.**

In [1]:
data_url = "https://virginia.box.com/shared/static/nvy6nmwe67wc6dfj5zqfmqiqnnjk5jb1.csv"

In [9]:
import pandas as pd
import seaborn as sns

flights = pd.read_csv(data_url)
flights.head()

   Unnamed: 0  Years    Months  Passengers
0           0   1949   January         112
1           1   1949  February         118
2           2   1949     March         132
3           3   1949     April         129
4           4   1949       May         121

In [14]:
flights.value_counts(['Months','Years']).head(1)

Months   Years
January  1949     1
Name: count, dtype: int64

In [15]:
group_cols = ['Months','Years']
measure_cols = ['Passengers']


flight_details = flights.pivot(index='Months',columns='Years',values='Passengers')

flight_details

Years,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
Months,,,,,,,,,,,,
April,129,135,163,181,235,227,269,313,348,348,396,461
August,148,170,199,242,272,293,347,405,467,505,559,606
December,118,140,166,194,201,229,278,306,336,337,405,432
February,118,126,150,180,196,188,233,277,301,318,342,391
January,112,115,145,171,196,204,242,284,315,340,360,417
July,148,170,199,230,264,302,364,413,465,491,548,622
June,135,149,178,218,243,264,315,374,422,435,472,535
March,132,141,178,193,236,235,267,317,356,362,406,419
May,121,125,172,183,229,234,270,318,355,363,420,472
November,104,114,146,172,180,203,237,271,305,310,362,390
October,119,133,162,191,211,229,274,306,347,359,407,461
September,136,158,184,209,237,259,312,355,404,404,463,508

In [7]:
flight_details2 = flights.set_index(['Months','Years'])['Passengers'].unstack()
flight_details2

Years,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
Months,,,,,,,,,,,,
April,129,135,163,181,235,227,269,313,348,348,396,461
August,148,170,199,242,272,293,347,405,467,505,559,606
December,118,140,166,194,201,229,278,306,336,337,405,432
February,118,126,150,180,196,188,233,277,301,318,342,391
January,112,115,145,171,196,204,242,284,315,340,360,417
July,148,170,199,230,264,302,364,413,465,491,548,622
June,135,149,178,218,243,264,315,374,422,435,472,535
March,132,141,178,193,236,235,267,317,356,362,406,419
May,121,125,172,183,229,234,270,318,355,363,420,472
November,104,114,146,172,180,203,237,271,305,310,362,390
October,119,133,162,191,211,229,274,306,347,359,407,461
September,136,158,184,209,237,259,312,355,404,404,463,508