# Week 2 Challenge 2

DS 2023 | Communicating with Data

## Overview

In today's challenge, you will apply what you have learned about the creating wide tables using Pandas.

Work in groups to perform the tasks.

When finished, submit a URL to this notebook in your GitHub repo to today's participation assignment.

## Set Up

We import the `experiment` dataset from from Plotly.

The meaning of the experiment is unknown.

In [1]:
import pandas as pd
from plotly.express import data as pxdata

In [2]:
df = pxdata.experiment()
df

    experiment_1  experiment_2  experiment_3  gender      group
0      96.876065     93.417942     73.033193    male    control
1      87.301336    129.603395     66.056554  female    control
2      97.691312    106.187916    103.422709    male  treatment
3     102.978152     93.814682     56.995870  female  treatment
4      87.106993    107.019985     72.140292    male    control
..           ...           ...           ...     ...        ...
95    108.156964    105.971541     64.524029  female  treatment
96     91.739992    111.125377     64.260993    male    control
97     95.410347     84.448322     75.505991  female    control
98    106.362406    115.522382    123.469689    male  treatment
99     94.269237    104.651064     92.387490  female  treatment

[100 rows x 5 columns]

## Tasks

### Task 1: Define group and measure variables

Hint: create lists `measure_cols` and `group_cols` with the appropriate column names as members.

In [5]:
group_cols=['gender','group']
measure_cols=['experiment_1','experiment_2','experiment_3']

### Task 2: Create analytic column

Create a new column `exp_mean` that holds the average of the measurement columns.

Here's how to do this:

```python
df['exp_mean'] = df[measure_cols].mean(axis=1)
```

In [7]:
df['exp_mean'] = df[measure_cols].mean(axis=1)

df

    experiment_1  experiment_2  experiment_3  gender      group    exp_mean
0      96.876065     93.417942     73.033193    male    control   87.775733
1      87.301336    129.603395     66.056554  female    control   94.320428
2      97.691312    106.187916    103.422709    male  treatment  102.433979
3     102.978152     93.814682     56.995870  female  treatment   84.596235
4      87.106993    107.019985     72.140292    male    control   88.755757
..           ...           ...           ...     ...        ...         ...
95    108.156964    105.971541     64.524029  female  treatment   92.884178
96     91.739992    111.125377     64.260993    male    control   89.042121
97     95.410347     84.448322     75.505991  female    control   85.121553
98    106.362406    115.522382    123.469689    male  treatment  115.118159
99     94.269237    104.651064     92.387490  female  treatment   97.102597

[100 rows x 6 columns]

### Task 3: Aggregate 

Aggregate the dataframe grouping by the group columns and getting the mean of `exp_mean`.

In [15]:
df1 = df.groupby(group_cols)['exp_mean'].mean()
df1

gender  group
female  control       99.420267
        treatment    101.811400
male    control       98.348415
        treatment    100.955860
Name: exp_mean, dtype: float64

### Task 4: Widen

Widen the table so that the domain of one group variable is projected onto axis 0 and the other is projected onto axis 1.

In [9]:
df.value_counts()

experiment_1  experiment_2  experiment_3  gender  group      exp_mean
96.876065     93.417942     73.033193     male    control    87.775733     1
87.301336     129.603395    66.056554     female  control    94.320428     1
97.691312     106.187916    103.422709    male    treatment  102.433979    1
102.978152    93.814682     56.995870     female  treatment  84.596235     1
87.106993     107.019985    72.140292     male    control    88.755757     1
                                                                          ..
108.156964    105.971541    64.524029     female  treatment  92.884178     1
91.739992     111.125377    64.260993     male    control    89.042121     1
95.410347     84.448322     75.505991     female  control    85.121553     1
106.362406    115.522382    123.469689    male    treatment  115.118159    1
94.269237     104.651064    92.387490     female  treatment  97.102597     1
Name: count, Length: 100, dtype: int64

In [19]:
#unique observations, so you can proceed with pure reshaping

df2 = df1.unstack()
df2

group     control  treatment
gender
female  99.420267  101.81140
male    98.348415  100.95586

### Task 5: Answer Question

Why do we use the argument `axis=1` in Task 2?

In [21]:
#Since we want to calculate the mean for the experiments, we have to use axis 1 to calculate the values, which are horizontally placed.

## Submit

Submit a URL to this document as your participation for today.