# Week 2 Challenge 3

DS 2023 | Communicating with Data

In this week's challenge, read the data URL provided into a dataframe and then convert it into a wide table using both the pivoting method and the unstacking method.

The dataset has two grouping columns and one measurement column.

You may not use the general function provided in the notebook we went over in class, but you may certainly apply the pattern it contains. 

Remember that you first need to determine if the grouping column combindations are unique over the observations.

To get credit for this activity, push your notebook to your course repo and submit the URL to Canvas.

Submit your work regardless of if you completed the task.

**You are encouraged to work in groups.**

In [8]:
data_url = "https://virginia.box.com/shared/static/nvy6nmwe67wc6dfj5zqfmqiqnnjk5jb1.csv"

In [9]:
import pandas as pd
import seaborn as sns

flight_details = pd.read_csv(data_url)
flight_details.head()

   Unnamed: 0  Years    Months  Passengers
0           0   1949   January         112
1           1   1949  February         118
2           2   1949     March         132
3           3   1949     April         129
4           4   1949       May         121

In [13]:
a_g1 = 'Years'
a_g2 = 'Months'
a_m = 'Passengers'

In [14]:
#check for uniqueness
flight_details.value_counts([a_g1,a_g2]).head(1)

Years  Months
1949   January    1
Name: count, dtype: int64

In [21]:
#no values greater than 1, so unique

In [22]:
#RESHAPING: Pivoting Method
flight_details.pivot(index=a_g1, columns=a_g2, values=a_m)

Months,April,August,December,February,January,July,June,March,May,November,October,September
Years,,,,,,,,,,,,
1949,129,148,118,118,112,148,135,132,121,104,119,136
1950,135,170,140,126,115,170,149,141,125,114,133,158
1951,163,199,166,150,145,199,178,178,172,146,162,184
1952,181,242,194,180,171,230,218,193,183,172,191,209
1953,235,272,201,196,196,264,243,236,229,180,211,237
1954,227,293,229,188,204,302,264,235,234,203,229,259
1955,269,347,278,233,242,364,315,267,270,237,274,312
1956,313,405,306,277,284,413,374,317,318,271,306,355
1957,348,467,336,301,315,465,422,356,355,305,347,404
1958,348,505,337,318,340,491,435,362,363,310,359,404
1959,396,559,405,342,360,548,472,406,420,362,407,463
1960,461,606,432,391,417,622,535,419,472,390,461,508

In [23]:
#RESHAPING: Unstacking Method
flight_details.set_index([a_g1, a_g2])[a_m].unstack()

Months,April,August,December,February,January,July,June,March,May,November,October,September
Years,,,,,,,,,,,,
1949,129,148,118,118,112,148,135,132,121,104,119,136
1950,135,170,140,126,115,170,149,141,125,114,133,158
1951,163,199,166,150,145,199,178,178,172,146,162,184
1952,181,242,194,180,171,230,218,193,183,172,191,209
1953,235,272,201,196,196,264,243,236,229,180,211,237
1954,227,293,229,188,204,302,264,235,234,203,229,259
1955,269,347,278,233,242,364,315,267,270,237,274,312
1956,313,405,306,277,284,413,374,317,318,271,306,355
1957,348,467,336,301,315,465,422,356,355,305,347,404
1958,348,505,337,318,340,491,435,362,363,310,359,404
1959,396,559,405,342,360,548,472,406,420,362,407,463
1960,461,606,432,391,417,622,535,419,472,390,461,508